---
apiVersion: v1
kind: Secret
metadata:
  name: weijer1968-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-aro24/weijer1968-gateway-gitops
